### ISSUE TITLE
SPL ArrayObject as Collection

### ISSUE THREAD

**Issue by semmel** [tarsana/functional#5]
Are [ArrayObjects](http://php.net/manual/de/class.arrayobject.php) welcome as collections?

There is nothing wrong with `array`. Coming from JavaScript it's just that one should remember that Arrays are copied by value unless passed by reference `&$myArray`. 

On the other hand `ArrayObject` may be better suited for serialization. 

Many functions in the [List category](https://github.com/tarsana/functional/blob/master/docs/list.md) work on `ArrayObject` collections too. However those functions in the [Object category](https://github.com/tarsana/functional/blob/master/docs/object.md) get confused when the collection is an `ArrayObject`. 

Perhaps the implementation could support it by adding three more cases:
```php
if ($object instanceof ArrayObject) {
   if ($object->getFlags() == ArrayObject::ARRAY_AS_PROPS) {
      // use $object['key']
   }
   else if ($object->getFlags() == ArrayObject::STD_PROP_LIST) {
      // use $object->key
   }
   else {
      // can use both access methods above
   }
}
```

**Comment by webNeat** [comment]
Passing parameters by reference is not a good idea when using Functional Programming. I guess the simplest solution could be to convert the `ArrayObject` to an ordinary `array` using `getArrayCopy()`. Of course this will slow down the program but it's better then changing the state. What do you think ?

**Comment by semmel** [comment]
Yes, I agree that one should avoid changing state and thus that immutable objects are much better.

Having a background in C++ and JavaScript I am still unfamiliar with the variety of collections in PHP. 

My remark about passing by reference was misleading, please ignore it. But I really like to use PHP object collections like `SplObjectStorage` and `ArrayObject` with *functional*.
I found out that they support `Iterator` and thus are suitable for `foreach` iteration and thus work well with the List Category functions in *functional* - very good! 

However the functions in the [Object Category](https://github.com/tarsana/functional/blob/master/docs/object.md) like `get` that are passed a PHP object collection assume that it is a regular object and not a list-like collection. I will add an example what I mean later with more time.

Btw.
I am really glad :heart:  to find in *functional* a Ramda equivalent for PHP! It saves me a ton of time. Great work!

Just to explain my remark about passing by reference:
It puzzles me that in PHP then passing an `array` (with immutable, const entries) into a function it gets completely copied (i.e. duplicated). In JavaScript or with PHP objects like `ArrayObject` or `SplObjectStorage` just a handle to that collection gets passed to the function. It's not the performance I care of, but I occasionally need to mutate arrays.

**Comment by webNeat** [comment]
I guess if we start to handle different types of collections; things will become complicated very quickly. 

For example:

```php
$set = new SplObjectStorage();

$set->attach((object) ['name' => 'foo']);
$set->attach((object) ['name' => 'bar']);

$collection = new ArrayObject([
	(object) ['name' => 'lorem'],
	(object) ['name' => 'ipsum']
]);

$all = F\concat($set, $collection); // What should this return ??
```

A good solution for me is to keep the [List](https://github.com/tarsana/functional/blob/master/docs/list.md) and [Object](https://github.com/tarsana/functional/blob/master/docs/object.md) functions working only with `array`s and to have the following additional functions:

```php
array toArray(ArrayObject|SplObjectStorage $collection); // converts the collection to an array
ArrayObject toArrayObject(array $array, int $flags); // simply calls the ArrayObject constructor
SplObjectStorage toObjectStorage(array $array); // Creates a new SplObjectStorage and fills it with the array items using values as objects and keys as data.
```

This way you can do things like

```php
$numbers = new ArrayObject([-1, -2, 1, 5]);
$positives = toArrayObject(F\filter(F\gte(F\__(), 0), toArray($numbers)));
```

What do you think ?

**Comment by semmel** [comment]
I think that a purpose of any library is to reduce boilerplate code, thus to make the code more readable and provide higher abstraction. Forcing wrappers `toArray` and `toArrayObject` for every *Functional* call when using other data structures lets me type a lot of unnecessary code.

I think different collection types can be handled. Right now *Functional* already works on `String` `array` associative array and `Object`.

```php
$all = F\concat($set, $collection); // What should this return ??
```
I am not sure about exception handling in Php but I think it should throw an error.
`F\concat` already bails out when feeding it with inputs of different type: 
```php
Tarsana\Functional\concat([], "well");
// PHP Warning:  array_merge(): Argument #1 is not an array
```
So no difference here to `$set` and `$collection`. And it is the same thing *Ramda's* concat does.

**Comment by webNeat** [comment]
The difference between `array` and `string` in PHP and Javascript is that in PHP they are considered as *primitive types* (just like `int` and `char` in C++) while in Javascript everything is an `Object`. This feature helps **Ramda** to handle different types of containers simply by dispatching to their corresponding methods. Maybe I should use the same approach and start to use object containers instead of handling primitive data types; Something like:

```php
namespace Tarsana\Functional;

interface Collection {
    /**
     * Gets the internal items as an array.
     * @return array
     */
    public function toArray();
    /**
     * Gets a new container with the given items.
     * @param  array $items
     * @return Collection
     */
    public function fromArray(array $items);
    // Collection methods ...
    public function map(callback $fn);
    public function filter(callback $fn);
    public function concat(Collection $c);
    // ...
}

trait CollectionMethods {
    private $items;
    // Collection methods implementation
    public function map(callback $fn) { ... }
    public function filter(callback $fn) { ... }
    public function concat(Collection $c) { ... }
    // ...
}

class ArrayObject extends \ArrayObject implements Collection {
    use CollectionMethods;
    abstract public function toArray() { ... }
    abstract public function fromArray(array $items) { ... }
}

class SplObjectStorage extends \SplObjectStorage implements Collection {
    use CollectionMethods;
    abstract public function toArray() { ... }
    abstract public function fromArray(array $items) { ... }
}
```

*(Since PHP doesn't allow multiple inheritance like C++ does; I will be using [Traits](http://php.net/manual/fr/language.oop5.traits.php) which are a way to re-use the code in a modular way)*

This way `Tarsana\Functional\ArrayObject` and `Tarsana\Functional\SplObjectStorage` will be handled by all *List functions*.

This also gives the user of the library the possiblity to make any class supported as a Collection just by implementing the `Collection` interface.

The same approach will be used to handle strings and objects/associative arrays. I am not sure but maybe this will improve the performance of the library as well :)

I created a [new branch](https://github.com/tarsana/functional/tree/data-containers) to try this.

**Comment by semmel** [comment]
I don't think it is bad that this does not work:
```php
Tarsana\Functional\concat([], "well");
```
It's simply a misuse by the caller.

I can understand the motivation. Let me see if I understand it right:

Data goes in and out of my program logic from various heterogenous I/O sources:
* Web APIs returning JSON
* persistent storage (e.g. a database)
* ...

all delivered from different Php I/O libraries and Apis as some Php data type: `String`, `array`, associative `array`, `ArrayObject` associative `ArrayObject`, `SplObjectStorage`, associative `SplObjectStorage`, `Ds\Map` (associative), `Ds\Set`, `Ds\Vector`, `Ds\Sequence`, ....

All I want is to run a few transformations on the incoming data and deliver it to the receiving end. In the best case in immutable fashion without touching the data and ignoring the particular data format.

For that I 
* first define my operations using the *Functional* curried, data-last toolbox functions. And 
* second call the function composition on the data.

With your proposed `Tarsana\Functional\Collection` class I would have to wrap those I/O Apis in such a way that the data transformed from/to `Tarsana\Functional\Collection`. If such a wrapper does not exist I would have to write my own.. (E.g. for [php-ds](http://docs.php.net/manual/en/book.ds.php)).

On the other hand (like it is now) if the implementation of the functions of *Functional* is able to distinguish dynamically the type of the collection there is no need for a data type wrapper: The data format is not altered.

In both cases the implementation will dispatch to the appropriate data type method if available E.g:
```php
function map(callable $fn, $collection) {
   if ($collection instanceof \Ds\Vector) {
      return $collection.map($fn);
  }
  ...
}
```
In #6 I propose the way that the implementation can distinguish between data types, but I NOT if the are intended as lists or associative key-value stores.

for list collections or associative `array`* | for key-value collections
----- | -----
filter | filter_values
map | map_values
... | ...

\* when dispatching to `array_` functions it just works.

I agree that it is confusing having related but differently named free-standing functions for lists and associative arrays.

Even in *Ramda* there are a few of those pairs:

for lists | for objects 
------- | ------- 
forEach | forEachObjIndexed 
of | objOf

**Comment by webNeat** [comment]
Ok so for now you are requesting support for:

- [ArrayObject](http://php.net/manual/en/class.arrayobject.php)

- [SplObjectStorage](http://php.net/manual/en/class.splobjectstorage.php)

- [Ds\Vector](http://docs.php.net/manual/en/class.ds-vector.php)

- [Ds\Map](http://docs.php.net/manual/en/class.ds-map.php)

- [Ds\Set](http://docs.php.net/manual/en/class.ds-set.php)

I will add support for these collections and make it easy to add new collections in the future. The only thing you will need to do is to use `Tarsana\Functional\Collections\ClassName` instead of `\ClassName` for each one of `ArrayObject`, `SplObjectStorage`, `Ds\Vector`, `Ds\Map` and `Ds\Set`.

```php
use Tarsana\Functional as F;
use Tarsana\Functional\Collections\ArrayObject;
use Tarsana\Functional\Collections\Ds\Vector;

$nums = new ArrayObject([1, -2, 3]);
$vector = new Vector([4, 5]);

F\filter(F\gt(__(), 0), $nums); //=> ArrayObject([1, 3])
F\concat($nums, $vector); //=> ArrayObject([1, -2, 3, 4, 5])
F\concat($vector, $nums); //=> Vector([4, 5, 1, -2, 3])
// and so on ...
```

(I didn't include `Ds\Stack`, `Ds\Deque`, ... because these are not generic collections and should not support all operations).

Will that solve your issue ?

**Comment by semmel** [comment]
Hi @webNeat 
>Ok so for now you are requesting support for...

don't get me wrong, I am not *requesting* anything. I am in no position to request anything from a free open source project. There is no hurry to implement anything sacrificing the *library design goals*. I am just offering collaboration.

I am comfortable with *Ramda* on JS. I take it as an algorithm toolkit and apply it to widely-used, established data structures which happen to come from other APIs plugged into my application **and** my own data structures.  When programming in Php I would like to keep that style. And thus I found *Functional*. 

*Functional* would already be a great help if it works on `array` and associative `array`. That is in most cases working. 

However I doubt that `array` is the ultimate Php collection. If it were, why are there so many other? I just would like to **consider** opening *Functional* for the most common other collection types. 

*Functional* (like *Ramda*) can connect different layers and modules in an application. Those layers and modules usually offer and take data in a **standard** format. I think it is unwise to force users of *Functional* to write data wrappers for other layers of the application or the authors of that other layers to support a foreign data type like `Tarsana\Functional\Collections\ArrayObject`. In my experience that will not happen. 

So I am very sceptical about the `Tarsana\Functional\Collections` idea. I guess it has no place in a functional library and it will be hard to maintain as well.

That's why I wrote #6 - to demonstrate that you don't need to change the Api of *Functional* or the design goals. When I have time I will adapt #6 to comply with the new Contribution Guide.

Btw. which Php versions do you target? Hopefully not very old ones 😏 

Best regards
Semmel

**Comment by webNeat** [comment]
> However I doubt that array is the ultimate Php collection.

In PHP, [`array` is the **only standard** way the represent collection of data](http://stackoverflow.com/a/22407/1487270). It's the equivalent of `Array` and `Object` in Javascript. All other collection types are based on it.

>  If it were, why are there so many other ?

All these collection types are part of PHP Extensions and not the core language. They are here to provide OOP APIs and some additional features/optimizations. But most of them are basically just wrappers over `array`. That's why most of them can be constructed from and exported as `array`.

That's why I want to keep functions on this library handling `array` and keep conversions from/to other collection types outside the library. Since there is a variety of collection types out there; I let the user choose which ones to use and handle the conversion himself.

**Comment by semmel** [comment]
>All these collection types are part of PHP Extensions and not the core language.

Really?
[from the SPL Installation Manual:](http://php.net/manual/en/spl.installation.php)
>As of PHP 5.3.0 this extension can no longer be disabled and is therefore always available.

SPL may be an extension though but just in theory.

>They are here to provide OOP APIs and some additional features/optimizations. 

The same holds for `Array` and `Object` in JavaScript. But functional programming works well on that types.

>But most of them are basically just wrappers over array. That's why most of them can be constructed from and exported as array.

Implementing an Object -> Data map like `SplObjectStorage` with `array` maybe not so nice - in terms of performance as well. I don't see any `toArray` or `fromArray` methods. Could write my own but that would require iterating over the whole collection in a `foreach` loop.

Again: I don't think it is difficult to incrementally add support for other collections. In #6 I see to make the code reusable (e.g. `filter` and `map` can both use `reduce`). Please have a look on it. 

Otherwise we might finish this discussion for now.
